name: Deploy emha fully
on:
  push:
    branches:
      - production # This triggers the deploy when you push to this branch
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build React
        run: |
          cd agri_frontend
          npm install
          npm run build
      - name: Sync Frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./agri_frontend/dist/
          server-dir: /home9/emhafarm/public_html/

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: FTP Deploy Backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./agri_backend/ # Path to your Node files
          server-dir: /home9/emhafarm/api.emhafarm.in/ # The folder you set in cPanel Node Setup
          exclude: |
            node_modules/**
            .git/**
            .github/**
            .env

      - name: Trigger Restart
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./restart/
          server-dir: /home9/emhafarm/api.emhafarm.in/tmp/
          dangerous-clean-slate: true
